name: muyiwas_visuals_portfolio_builder
description: A portfolio creator app for designers to showcase their work

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^2.18.0
  firebase_auth: ^4.12.0
  cloud_firestore: ^4.8.0
  google_sign_in: ^6.1.0
  provider: ^6.1.1
  image_picker: ^1.0.4
  qr_flutter: ^4.2.0
  flutter_svg: ^2.0.7
  cached_network_image: ^3.3.0
  intl: ^0.18.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700

flutter_native_splash:
  color: "#6A35FF"
  image: assets/images/splash_logo.png
  android: true
  ios: true
  web: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/launcher_icon.png"
  adaptive_icon_background: "#6A35FF"
  web: true
  windows: true
  macos: true
  linux: true