// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
      return  web;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrUM6XSbFyr0n_KrroldpdwZc2lqYrL1k',
    appId: '1:324429753175:web:480d41f4e0c95834b8ac12',
    messagingSenderId: '324429753175',
    projectId: 'muyiwa-visual-stories-db',
    authDomain: 'muyiwa-visual-stories-db.firebaseapp.com',
    storageBucket: 'muyiwa-visual-stories-db.firebasestorage.app',
    measurementId: 'G-WH2HRL1F28',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6GCs50LC83O06t0UmAj-5Zh7-uNgiisk',
    appId: '1:324429753175:android:3322fd99a927b073b8ac12',
    messagingSenderId: '324429753175',
    projectId: 'muyiwa-visual-stories-db',
    storageBucket: 'muyiwa-visual-stories-db.firebasestorage.app',
  );
}
